using System;
Console.WriteLine("Inicializacion de la carga de Datos del Personaje");
Console.WriteLine("Carga del Tipo de Personaje");
Console.WriteLine("1- Soldado Moderno");
Console.WriteLine("2- Guerrero Mediaval");
Console.WriteLine("3- Soldado Interestelar");
Console.WriteLine("4- Alien");
Random numRan= new Random();
int TipoJugador;
TipoJugador=numRan.Next(4);
Console.WriteLine($"Seleccion: {TipoJugador+1}");
Console.WriteLine("Ingrese su Nombre");
int nom=numRan.Next(5);
//nom = Console.ReadLine();
Console.WriteLine(nom);
Console.WriteLine("Seleccionando apodo");
Console.WriteLine("1- Destructor");
Console.WriteLine("2- Malote");
Console.WriteLine("3- Viejo");
Console.WriteLine("4- Fantasma");
Console.WriteLine("5- Nerd");
int ApodoJugador;
ApodoJugador=numRan.Next(5);
Console.WriteLine($"Seleccion: {ApodoJugador+1}");
Console.WriteLine("Carga datos de Nacimiento");
DateTime actual = DateTime.Now;
DateTime inicio = actual.AddYears(-300);
DateTime nace = inicio.AddDays(numRan.Next(0,(actual-inicio).Days));
Console.WriteLine("Fecha de nacimiento: {0:d}\n", nace.Date);
Personaje jugador1 = new Personaje(TipoJugador,nom,ApodoJugador,nace);
Console.WriteLine("************************");
jugador1.MuestraDatos();
Console.WriteLine();
jugador1 = new Personaje();
jugador1.MuestraCaracter();
Console.WriteLine("\nFin.");